version: '3.8'

services:
  api:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - nats

  inventory:
    build: ./inventory
    ports:
      - "50052:50052"
    depends_on:
      - api
  
  order:
    build: ./order
    ports:
      - "50053:50053"
    volumes:
      - "./order/storage/:/app/storage"
    depends_on:
      - api
  
  auth:
    build: ./auth
    ports:
      - "50051:50051"
    depends_on:
      - api
    
  producer:
    build: ./producer
    ports:
      - "8081:8081"
    depends_on:
      - api
  
  consumer:
    build: ./consumer
    depends_on:
      - producer
    
  nats:
    image: nats
    ports:
      - "4222:4222"

  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=REDIS
      - REDIS_USER=REDIS
      - REDIS_USER_PASSWORD=REDIS
    ports:
      - "6380:6379"
    depends_on:
      - api